repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or:
          - css
          - javascript

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
